# -*- coding: utf-8 -*-
"""P4G - error treatment in exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o_c6WFGSgac5ezxv-YzuFPS9MASy8nR2

**Estimating recombination frequency - error treatment**

Write a program that estimates gene distances based on the frequencies of the recombinant genotypes and the non-recombinant genotypes

for example:

AB: 132 (non-recombinant)

ab: 145 (non-recombinant)

aB: 11 (recombinant)

Ab: 13 (recombinant)

Write an error treatment code that warns the user to type valid data whenever he/she types an invalid data type
"""

def validInt(question):
  while True:
    try:
      n = int(input(question))
    except:
      print('Invalid data type! Type an integer number')
    else:
      break
  return n

nonrecgen1 = validInt('How many non-recombinant individuals of genotype 1: ')
nonrecgen2 = validInt('How many non-recombinant individuals of genotype 2: ')
recgen1 = validInt('How many recombinant individuals of genotype 1: ')
recgen2 = validInt('How many recombinant individuals of genotype 2: ')

RF = (recgen1 + recgen2)/(recgen1 + recgen2 + nonrecgen1 + nonrecgen2)
RF = RF*100

print(f'The recombination frequency is approximately {RF}%')