# -*- coding: utf-8 -*-
"""P4G - base content in DNA sequence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhijoA6eN3wbmCpaGXlJ4PovQIWLH63B

**Extracting the AT/CG content**


Write a function that extracts the proportion of A-T or C-G in a DNA sequence. The function must have two parameters:

1- Sequence, i.e. the sequence to be analyzed

2- The base (A,T,C,G) of the base-pair to be analyzed (A-T, or C-G)
"""

def basePairProportion(dna,base):
  baseProportion = dna.count(base)
  basePairing = {'A':'T','T':'A','C':'G','G':'C'}
  secondBase = basePairing[base]
  secondBaseProportion = dna.count(secondBase)
  basePairAmount = baseProportion + secondBaseProportion
  percentage = (basePairAmount/len(dna))*100
  return percentage

dna1 = 'CGATCGATCGATCTGCTGATTAGTGCGATCGTAGTCGTATCGTATGCTAGTGCTATCAGCTCGT'
dna2 = 'CGTACGACTACGGACTATCATCGACTACTGATCGTTGTGTGTGTCGTACGATAGCTAGACTATG'

basePairProportion(dna1,'A')

basePairProportion(dna1, 'A') + basePairProportion(dna1, 'G')