# -*- coding: utf-8 -*-
"""P4G - population genetics problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvwCdswX43CX3GpCm8BpQOHMQQPtA_pw

#Using the Hardy Weinberg Theorum of population genetics

A hypothetical population has 2500 individuals. Scientists are investigating two alleles, P and Q. The number of individuals with each genotype is as follows:

**PP**: 1200

**PQ**: 745

**QQ**: 555

With the numbers above, calulate the frequency of each allele (0 to 1) and the chi-square for this population

**Steps:**

1) Calculate the frequency of each allele
2) Calculate the expected number for each genotype
3) Calculate the chi square based on the number of observed and expected individuals
"""

#Number of individuals

PPobs = int(input('Number of PP individuals: '))
PQobs = int(input('Number of PQ individuals: '))
QQobs = int(input('Number of QQ individuals: '))

n = PPobs + PQobs + QQobs

nObs = (PPobs,PQobs,QQobs)

#Calculating the allele frequency

def alleleFreq(homo,hetero,n):
  return (2*homo + hetero)/(2*n)

freqP = alleleFreq(PPobs,PQobs,n)
freqQ = alleleFreq(QQobs,PQobs,n)

print(freqP)
print(freqQ)
print(freqP + freqQ)

#Expected frequency of each genotype

expPP = freqP**2*n
expQQ = freqQ**2*n
expPQ = freqP*freqQ*2*n

nExp = (expPP,expPQ,expQQ)

print(nObs)
print(nExp)

#Obtaining the chi square

def chisquare(obs,exp):
  chisquare = 0
  count = 0
  while count < len(obs):
    delta = (obs[count]-exp[count])**2/(exp[count])
    chisquare = chisquare + delta
    count = count + 1
  return chisquare

chisquare(nObs,nExp)