# -*- coding: utf-8 -*-
"""P4G - ORF finder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A4vxx1IU-tAR8xwnB_7FVU32n5axpN6Q

#Challenge 1: ORF finder

Write a code that finds all ORF's in a pre-mRNA sequence in order to generate a processed RNA sequence.

ex:

seq -> GCA**AUG**CCUUUCUUACCUCCUAACCCU**UGA**CCUUAUACA**UGA**UUUAUGUUU**AUG**CCUCCUCCCGGGAAC**UAA**CACGCAGCG**UAG**

ORF's:

1) **AUG**CCUUUCUUACCUCCUAACCCU**UGA**

2) **AUG**CCUCCUCCCGGGAAC**UAA**
"""

rnaSeq = 'GCAAUGCCUUUCUUACCUCCUAACCCUUGACCUUAUACAUGAUUUAUGUUUAUGCCUCCUCCCGGGAACUAACACGCAGCGUAG'

start = 0
end = 3

orf = ''

orfs = []
initialize = False

while start < len(rnaSeq)-3:
  if rnaSeq[start:end]=='AUG':
    initialize = True
  elif rnaSeq[start:end] == 'UGA' or rnaSeq[start:end] == 'UAA' or rnaSeq[start:end] == 'UAG':
    initialize = False
    if len(orf)>0:
      orfs.append(orf)
    orf = ''

  if initialize == True:
    orf += rnaSeq[start:end]
  start += 3
  end += 3

orfs