# -*- coding: utf-8 -*-
"""P4G - polypeptide sequence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ibXBvmT-ComHPEooLmGzDz1MLsIRuxX

# Polypeptide analysis
Given some polypeptide sequence (each letter represents an aminoacid), write code that

a) Assess whether the polypetide sequence has methionine (M) or not

b) Assess whether the polypeptide sequence has more than 10 aa's or not
"""

polypeptide = 'ABHYFEHBVBBBBA'

if len(polypeptide) > 10:
  if 'M' in polypeptide:
    print('The polypeptide has more than 10 aas and has methionine')
  else:
    print('The polypeptide has more than 10 aas but doesnt have methionine')
else:
  if 'M' in polypeptide:
    print('The polypeptide doenst have more than 10 aas but it has methionine')
  else:
    print('The polypeptide doenst have more than 10 aas and it doenst have methionine')