# -*- coding: utf-8 -*-
"""P4G - Random DNA sequence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PiWSSDrYMMZ7Y2r_74rzaqfRSVACiIeP

**Generating a random DNA sequence**


Write a function that generates a random DNA sequence. This function must receive the sequence length as the only parameter

For example:

generateDNAseq(10) ---> AGTGCGGATC

generateDNAseq(13) ---> AGTCGAGGCTGAC
"""

import random

def generateDNAseq(length):
  nucleotides = ('A','T','C','G')
  randomSeq = ''
  for nucleotide in range(length):
    randomSeq += random.choice(nucleotides)
  return randomSeq

generateDNAseq(50)