# -*- coding: utf-8 -*-
"""P4G - timing algorithm execution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OIsycUjP7FtwdJiKLRpII-fI6o1X6Tle

#Timing algorithm execution

Use the function of random sequence generation and the time module to evaluate how many seconds the algorithm takes to generate a sequence with  1000, 10,000, 100,000 and 1 million nucleotides
"""

import random

def random_sequence(length):
  sequence = ''
  nucleotides = ('A','C','G','T')
  for nucleotide in range(length):
    sequence += random.choice(nucleotides)
  return sequence

#time the algorithm execution

import time

before = time.time()

random_sequence(10000000)

after = time.time()

interval = after - before

print(f'{interval} seconds')