# -*- coding: utf-8 -*-
"""PG4 - transcription with dictionaries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fNnqhj-X-gOomWxwJXN2S2gSjoUojUP7

**DNA transcription**

Write a Python code that simulates the process of transcription from DNA to RNA, but this time, you must use dictionaries instead of using other methods

**Example**:


CCGTAGCGTAGC ---> GGCAUCGCAUCG
"""

seq = 'GCATCTAGTCGTCGATCTCGTAGTCTATCGATCTAGCCTGACT'

dna_to_rna = {'A':'U','C':'G','G':'C','T':'A'}

rna_seq = ''
for nucleotide in seq:
  rna_seq = rna_seq + dna_to_rna[nucleotide]

print(f'The RNA sequence is {rna_seq}')