# -*- coding: utf-8 -*-
"""P4G - position of codons.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u9QeOt7Kd4mQPCpLjvVwPds2PmZrdG29

# Position of start and termination codons
Write a code that:

a) returns the position where the start and termination codons begin

b) extracts the ORF (open reading frame) of the RNA sequence

Tips: The start codon is AUG and the termination codon may be UGA, UAA and UAG

Example:

GGCCCGAUGGGAGGAGGGCCCUUGGGAUGAUUUGACCGA

start codon: position 6 termination codon: position 32

ORF: AUGGGAGGAGGGCCCUUGGGAUGAUUUGA
"""

rna = 'AAAAUGUUUCCCGCGGCGGCGUGAUUUAGCGAC'

start = rna.find('AUG')
termination = rna.find('UGA')

print(f'The positions of the start and termination codons are {start} and {termination}, respectively')

orf = rna[start:termination+3]

print(f'ORF: {orf}')