# -*- coding: utf-8 -*-
"""P4G - RNA translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z5iPW4mdbDWpCsrTxthx86_JVNoY-8OP

**mRNA translation**

Write code that translates a processed RNA sequence into a polypeptide chain
"""

seqRNA = 'GCUAGCAUCGUCGUACUGCUACCGAUCGAUCUACGUACGUACUGACAUGAGGCUUGAGGCUAGC'

translation = {'UUU':'Phe','UUC':'Phe',
               'UUA':'Leu','UUG':'Leu','CUU':'Leu','CUC':'Leu','CUA':'Leu','CUG':'Leu',
               'AUU':'Ile','AUC':'Ile','AUA':'Ile',
               'AUG':'Met',
               'GUU':'Val','GUC':'Val','GUA':'Val','GUG':'Val',
               'UCU':'Ser','UCC':'Ser','UCA':'Ser','UCG':'Ser',
               'CCU':'Pro','CCC':'Pro','CCA':'Pro','CCG':'Pro',
               'ACU':'Thr','ACC':'Thr','ACA':'Thr','ACG':'Thr',
               'GCU':'Ala','GCC':'Ala','GCA':'Ala','GCG':'Ala',
               'UAU':'Tyr','UAC':'Tyr',
               'CAU':'His','CAC':'His',
               'CAA':'Gln','CAG':'Gln',
               'AAU':'Asn','AAC':'Asn',
               'AAA':'Lys','AAG':'Lys',
               'GAU':'Asp','GAC':'Asp',
               'GAA':'Glu','GAG':'Glu',
               'UGU':'Cys','UGC':'Cys',
               'UGG':'Trp',
               'CGU':'Arg','CGC':'Arg','CGA':'Arg','CGG':'Arg',
               'AGU':'Ser','AGC':'Ser',
               'AGA':'Arg','AGG':'Arg',
               'GGU':'Gly','GGC':'Gly','GGA':'Gly','GGG':'Gly',
               'UAA':'XXX','UAG':'XXX','UGA':'XXX'}

translation['UUU']

translation['AAG']

translation['CAG']

translation['GUU']

peptide = ''

start = 0
end = 3

while start < len(seqRNA)-3:
  peptide = peptide + translation[seqRNA[start:end]] + '-'
  start += 3
  end += 3

seqRNA

peptide