# -*- coding: utf-8 -*-
"""P4G - Sequence manipulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/116zUmQour1YCKrBvlByDWp31tKRIv-GW

#Challenge

Write a Python script that reads a genetic sequence. The program must display a menu to the user, allowing him/her to choose one of the following options


[1] Return the RNA sequence and write it into a file

[2] Return the complementary sequence and write it into a file

[3] Show the A-T content

[4] Show the C-G content
"""

sequence = str (input('Path of the file:'))

with open(sequence) as seq:
  seq2 = []
  count = 0
  for i in seq:
    if count > 0:
      seq2.append(i)
    count +=1

seq3 = ''.join(seq2)

seq

seq2

seq3

def transcription(seq):
  rna = ''
  dna_to_rna = {'A':'U','C':'G','T':'A','G':'C'}
  for char in seq:
    if char in dna_to_rna.keys():
      rna += dna_to_rna[char]
    else:
      rna += char
  return rna

rna = transcription(seq3)

rna

def complement(seq):
  comp = ''
  dna_to_comp = {'A':'U','C':'G','T':'A','G':'C'}
  for char in seq:
    if char in dna_to_comp.keys():
      comp += dna_to_comp[char]
    else:
      comp += char
  return comp

comp = complement(seq3)

comp

def atContent(seq):
  a = seq.count('A')
  c = seq.count('C')
  g = seq.count('G')
  t = seq.count('T')
  total = a+t+c+g
  at = (a+t)/total*100
  return at

at = atContent(seq3)

at

def cgContent(seq):
  a = seq.count('A')
  c = seq.count('C')
  g = seq.count('G')
  t = seq.count('T')
  total = a+t+c+g
  cg = (c+g)/total*100
  return cg

cg = cgContent(seq3)

cg

def writeSeq(seq):
  with open('sequence.txt', 'w') as processed_seq:
    processed_seq.write(seq)

def validInt(question):
  while True:
    try:
      n = int(input(question))
    except:
      print('Invalid data! Type an integer number')
    else:
      break
  return n

while True:

  option = validInt('''Choose an option:
[1]Return the complementary sequence
[2]Return the RNA sequence
[3]Return the A-T content (%)
[4]Return the C-G content (%)

''')

  if option == 1:
    writeSeq(comp)
    break
  elif option == 2:
    writeSeq(rna)
    break
  elif option == 3:
    print(f'The AT content (%) is {at}')
    break
  elif option == 4:
    print(f'The CG content (%) is {cg}')
    break
  else:
    print('Invalid option! Choose 1,2,3 or 4')