# -*- coding: utf-8 -*-
"""P4G - transcription.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WzFuqC_vuGL_dzUfNgnv_7BzEyWDEJYS

**DNA transcription**

Write a Python code that simulates the process of transcription from DNA to RNA

**Example**:


CCGTAGCGTAGC ---> GGCAUCGCAUCG

Sequence
"""

dna = str(input('Type the DNA sequence: '))

"""Conditionals"""

rna = ''

for nucleotide in dna:
  if nucleotide == 'T':
    rna += 'U'
  else:
    rna += nucleotide

print(f'The transcribed rna sequence is {rna}')