# -*- coding: utf-8 -*-
"""P4G - Working with fasta files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zLzMAh1qnNKTHIiLb440tN0eR8LsRQ0I

#Transcribing a DNA sequence from a fasta file

Go to some gene/genome repository and download some fasta file of some DNA sequence. Import the file to the COLAB environment and write a code that transcribes the sequence and generates a .txt file with the sequence transcribed
"""

with open('/content/sequence.fasta','r') as sarscov2:
  sequence = []
  count = 0
  for line in sarscov2:
    if count > 0:
      sequence.append(line)
    count += 1

sequence2 = ''.join(sequence)

sequence2

dna_to_rna = {'A':'U','T':'A','C':'G','G':'C'}
rnaSeq = ''
for character in sequence2:
  if character in dna_to_rna.keys():
    rnaSeq += dna_to_rna[character]
  else:
    rnaSeq += character

rnaSeq

#Creating a txt file for the RNA sequence
with open('rnaSeq.txt','w') as rna:
  rna.write(rnaSeq)