# -*- coding: utf-8 -*-
"""PG4 - molecule classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZMR5gEoF5SzAdRTeETmHJ0Op2fy8-qP-

#Biomolecule classifier

Write a code that takes a molecule as input and classify it as DNA or RNA by using conditional statements


For example:



**GCGUAGCUACGUCUAG** ----> This molecule is RNA

**CGTAGCGATGATCGAC** ----> This molecule is DNA

Input
"""

molecule = str(input('Type the molecule: ')).upper()

molecule

"""Conditional"""

if 'T' in molecule:
  print('This is a DNA molecule')
elif 'U' in molecule:
  print('This is RNA molecule')
else:
  print('Unknown type of molecule')