# -*- coding: utf-8 -*-
"""P4G - Allele inheritance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-RWJFFj9CA2rgDtKCPSkHBWkkc3u_wf-

**Allele inheritance**

Write a code that simulates the reproduction between two parents (AA, Aa or aa) and the show their offspring based on the probability of inheritance of each allele. The program must also show the percentage of each genotype in the offspring

**Example**:

genotype 1: AA

genotype 2: Aa

Offspring: 20


-> AA Aa AA aA AA AA AA aA Aa Aa AA AA aA Aa AA AA AA aA Aa aA

AA (%): 50
aa (%): 0
Aa (%): 50
"""

genotype1 = str(input('Genotype of parent 1: '))
genotype2 = str(input('Genotype of parent 2: '))

import random

alleles1 = (genotype1[0],genotype1[1])
alleles2 = (genotype2[0],genotype2[1])

alleles2

offspring = int(input('Number of individuals generated: '))

genotypes = []

for i in range(offspring):
  genotype = random.choice(alleles1) + random.choice(alleles2)
  genotypes.append(genotype)

genotypes

AA = 0
Aa = 0
aa = 0
for i in genotypes:
  if i == 'AA':
    AA += 1
  elif i == 'Aa' or i == 'aA':
    Aa += 1
  elif i == 'aa':
    aa += 1

percentageAA = AA/(offspring)*100
percentageAa = Aa/(offspring)*100
percentageaa = aa/(offspring)*100
print(f'Percentage of AA: {percentageAA}%')
print(f'Percentage of Aa: {percentageAa}%')
print(f'Percentage of aa: {percentageaa}%')