# -*- coding: utf-8 -*-
"""P4G - base pairing condition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WV51X5C11u9WyttFNThbpsCF1hWHGXRi

**Base pairing condition**


Write a program that asks the user to type a nitrogen base
according to the pairing rules.

The program must tell with which of the four bases  the chosen base must be paired

If the chosen base is not A,T,C or G, the program must say that this is not a DNA nitrogen base

**Extra**: as an extra, make sure that every time the user types an invalid base, the program
 warns the user that this is not a DNA base and asks him/her to type a valid
base again until he/she types A, G, C or T
"""

#Base-pairing rules
#A pairs with T
#C pairs with G

while True:
  base = str(input(f'Type a nitrogen base: '))
  if base != 'A' and base != 'T' and base != 'C' and base != 'G':
    print('this is not a valid DNA base')
  elif base == 'A':
    print('A pairs with T')
    break
  elif base == 'T':
    print('T pairs with A')
    break
  elif base == 'G':
    print('G pairs with C')
    break
  elif base == 'C':
    print('C pairs with G')
    break