# -*- coding: utf-8 -*-
"""P4G - function of recombination frequency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ddJqZpdFH-cqSSXk6b2QT3L9Ys9CosJv

**Function of recombination frequency**

Write a function that estimates the recombination frequency based on the number of recombinant and non recombinant genotypes
"""

def recombination_frequency(rec1,rec2,nonrec1,nonrec2,dec_places = 5):
  RF = (rec1+rec2)/(nonrec1+nonrec2+rec1+rec2)
  return round((RF*100),dec_places)

recombination_frequency(4,8,54,67,dec_places=2)