# -*- coding: utf-8 -*-
"""PG4 - Hamming distance calculation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1glzehhD77KXiQTmgj6uHoRuUAnE_MkIw

#**Hamming distance**

The hamming distance of two strings can be understood as the amount of characters that are different between these two strings.


Given two DNA sequences of the same length, write a code that calculates the hamming distance between the two strings and the similarity (%) between them.
"""

a = 'CGATGCTGCATGCTGACTGCTAGC'
b = 'CGCTGCTCCATTCTGACGGCTAGC'

count = 0
difference = 0
while count < len(a):
  if a[count] != b[count]:
    difference = difference + 1
  count = count + 1

percentageOfDifference = (difference/len(a))*100

difference

print(f'The hamming distance between the two sequences is {difference} and the similarity is {100-percentageOfDifference} %')