# -*- coding: utf-8 -*-
"""P4G - Estimating recombination frequency4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycKY54xEGqn8Tf6NsywfmO-sLCEsddi3

Write a program that estimates gene distances based on the frequencies of the recombinant genotypes and the non-recombinant genotypes for examples:

AB: 132 (non-recombinant)

ab: 145 (non-recombinant)

aB: 11 (recombinant)

Ab: 13 (recombinant)
"""

rec1 = int(input('Number of recombinant genotypes 1:  '))
rec2 = int(input('Number of recombinant genotypes 2:  '))
nonrec1 = int(input('Number of non-recombinant genotypes 1:  '))
nonrec2 = int(input('Number of non-recombinant genotypes 2:  '))

nonrec2

RF = 100*(rec1+rec2)/(rec1+rec2+nonrec1+nonrec2)

RF

print('The recombination frequency is estimated to be',round(RF,3),'%')