# -*- coding: utf-8 -*-
"""P4G - calculating allele frequencies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dFfOmT02GiZJNDTNT4YzNZ5sWS3HsI91

# Calculating allele frequencies

Write a Python code that asks the user the number of individuals with the genotypes pp, pq and qq in the population and then returns the frequencies of the two alleles (p and q) in the population.
"""

pp = int(input('Number of pp genotypes: '))
qq = int(input('Number of qq genotypes: '))
pq = int(input('Number of pq genotypes: '))

numberOfIndividuals = pp + qq + pq

numberOfIndividuals

#Frequencies of the alleles p and q
freqP = (2*pp + pq)/(numberOfIndividuals*2)
freqQ = (2*qq + pq)/(numberOfIndividuals*2)

freqQ+freqQ

print('The respective frequencies of all the alleles p and q are',round(freqP,2),'and',round(freqQ,2),'respectively!')