# -*- coding: utf-8 -*-
"""PG4 - DNA sequence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JQDIEdFT6J3DMpjhvOHmAuv9aDHQSLqf

# Sequence manipulation

Given some DNA sequence in lowercase letters:

a) Turn the characters into uppercase letters

b) Slice the string. The slice must include characters from the fifth to the tenth

c) Transcription:turn the DNA string into an RNA string
"""

dna = 'gacgatgcatcggcttacg'

dna.upper()

dna[4:10]

dna.replace('t','u')